/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scheme "github.com/volcano-sh/agentcube/client-go/clientset/versioned/scheme"
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MultiAgentRuntimesGetter has a method to return a MultiAgentRuntimeInterface.
// A group's client should implement this interface.
type MultiAgentRuntimesGetter interface {
	MultiAgentRuntimes(namespace string) MultiAgentRuntimeInterface
}

// MultiAgentRuntimeInterface has methods to work with MultiAgentRuntime resources.
type MultiAgentRuntimeInterface interface {
	Create(ctx context.Context, multiAgentRuntime *runtimev1alpha1.MultiAgentRuntime, opts v1.CreateOptions) (*runtimev1alpha1.MultiAgentRuntime, error)
	Update(ctx context.Context, multiAgentRuntime *runtimev1alpha1.MultiAgentRuntime, opts v1.UpdateOptions) (*runtimev1alpha1.MultiAgentRuntime, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, multiAgentRuntime *runtimev1alpha1.MultiAgentRuntime, opts v1.UpdateOptions) (*runtimev1alpha1.MultiAgentRuntime, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*runtimev1alpha1.MultiAgentRuntime, error)
	List(ctx context.Context, opts v1.ListOptions) (*runtimev1alpha1.MultiAgentRuntimeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *runtimev1alpha1.MultiAgentRuntime, err error)
	MultiAgentRuntimeExpansion
}

// multiAgentRuntimes implements MultiAgentRuntimeInterface
type multiAgentRuntimes struct {
	*gentype.ClientWithList[*runtimev1alpha1.MultiAgentRuntime, *runtimev1alpha1.MultiAgentRuntimeList]
}

// newMultiAgentRuntimes returns a MultiAgentRuntimes
func newMultiAgentRuntimes(c *RuntimeV1alpha1Client, namespace string) *multiAgentRuntimes {
	return &multiAgentRuntimes{
		gentype.NewClientWithList[*runtimev1alpha1.MultiAgentRuntime, *runtimev1alpha1.MultiAgentRuntimeList](
			"multiagentruntimes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *runtimev1alpha1.MultiAgentRuntime { return &runtimev1alpha1.MultiAgentRuntime{} },
			func() *runtimev1alpha1.MultiAgentRuntimeList { return &runtimev1alpha1.MultiAgentRuntimeList{} },
		),
	}
}
