/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scheme "github.com/volcano-sh/agentcube/client-go/clientset/versioned/scheme"
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SnapshotClassesGetter has a method to return a SnapshotClassInterface.
// A group's client should implement this interface.
type SnapshotClassesGetter interface {
	SnapshotClasses() SnapshotClassInterface
}

// SnapshotClassInterface has methods to work with SnapshotClass resources.
type SnapshotClassInterface interface {
	Create(ctx context.Context, snapshotClass *runtimev1alpha1.SnapshotClass, opts v1.CreateOptions) (*runtimev1alpha1.SnapshotClass, error)
	Update(ctx context.Context, snapshotClass *runtimev1alpha1.SnapshotClass, opts v1.UpdateOptions) (*runtimev1alpha1.SnapshotClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*runtimev1alpha1.SnapshotClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*runtimev1alpha1.SnapshotClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *runtimev1alpha1.SnapshotClass, err error)
	SnapshotClassExpansion
}

// snapshotClasses implements SnapshotClassInterface
type snapshotClasses struct {
	*gentype.ClientWithList[*runtimev1alpha1.SnapshotClass, *runtimev1alpha1.SnapshotClassList]
}

// newSnapshotClasses returns a SnapshotClasses
func newSnapshotClasses(c *RuntimeV1alpha1Client) *snapshotClasses {
	return &snapshotClasses{
		gentype.NewClientWithList[*runtimev1alpha1.SnapshotClass, *runtimev1alpha1.SnapshotClassList](
			"snapshotclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *runtimev1alpha1.SnapshotClass { return &runtimev1alpha1.SnapshotClass{} },
			func() *runtimev1alpha1.SnapshotClassList { return &runtimev1alpha1.SnapshotClassList{} },
		),
	}
}
