/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AgentRuntimeLister helps list AgentRuntimes.
// All objects returned here must be treated as read-only.
type AgentRuntimeLister interface {
	// List lists all AgentRuntimes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.AgentRuntime, err error)
	// AgentRuntimes returns an object that can list and get AgentRuntimes.
	AgentRuntimes(namespace string) AgentRuntimeNamespaceLister
	AgentRuntimeListerExpansion
}

// agentRuntimeLister implements the AgentRuntimeLister interface.
type agentRuntimeLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.AgentRuntime]
}

// NewAgentRuntimeLister returns a new AgentRuntimeLister.
func NewAgentRuntimeLister(indexer cache.Indexer) AgentRuntimeLister {
	return &agentRuntimeLister{listers.New[*runtimev1alpha1.AgentRuntime](indexer, runtimev1alpha1.Resource("agentruntime").GroupResource())}
}

// AgentRuntimes returns an object that can list and get AgentRuntimes.
func (s *agentRuntimeLister) AgentRuntimes(namespace string) AgentRuntimeNamespaceLister {
	return agentRuntimeNamespaceLister{listers.NewNamespaced[*runtimev1alpha1.AgentRuntime](s.ResourceIndexer, namespace)}
}

// AgentRuntimeNamespaceLister helps list and get AgentRuntimes.
// All objects returned here must be treated as read-only.
type AgentRuntimeNamespaceLister interface {
	// List lists all AgentRuntimes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.AgentRuntime, err error)
	// Get retrieves the AgentRuntime from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.AgentRuntime, error)
	AgentRuntimeNamespaceListerExpansion
}

// agentRuntimeNamespaceLister implements the AgentRuntimeNamespaceLister
// interface.
type agentRuntimeNamespaceLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.AgentRuntime]
}
