/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BrowserUseLister helps list BrowserUses.
// All objects returned here must be treated as read-only.
type BrowserUseLister interface {
	// List lists all BrowserUses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.BrowserUse, err error)
	// BrowserUses returns an object that can list and get BrowserUses.
	BrowserUses(namespace string) BrowserUseNamespaceLister
	BrowserUseListerExpansion
}

// browserUseLister implements the BrowserUseLister interface.
type browserUseLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.BrowserUse]
}

// NewBrowserUseLister returns a new BrowserUseLister.
func NewBrowserUseLister(indexer cache.Indexer) BrowserUseLister {
	return &browserUseLister{listers.New[*runtimev1alpha1.BrowserUse](indexer, runtimev1alpha1.Resource("browseruse").GroupResource())}
}

// BrowserUses returns an object that can list and get BrowserUses.
func (s *browserUseLister) BrowserUses(namespace string) BrowserUseNamespaceLister {
	return browserUseNamespaceLister{listers.NewNamespaced[*runtimev1alpha1.BrowserUse](s.ResourceIndexer, namespace)}
}

// BrowserUseNamespaceLister helps list and get BrowserUses.
// All objects returned here must be treated as read-only.
type BrowserUseNamespaceLister interface {
	// List lists all BrowserUses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.BrowserUse, err error)
	// Get retrieves the BrowserUse from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.BrowserUse, error)
	BrowserUseNamespaceListerExpansion
}

// browserUseNamespaceLister implements the BrowserUseNamespaceLister
// interface.
type browserUseNamespaceLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.BrowserUse]
}
