/*
Copyright The AgentCube Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CodeInterpreterLister helps list CodeInterpreters.
// All objects returned here must be treated as read-only.
type CodeInterpreterLister interface {
	// List lists all CodeInterpreters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.CodeInterpreter, err error)
	// CodeInterpreters returns an object that can list and get CodeInterpreters.
	CodeInterpreters(namespace string) CodeInterpreterNamespaceLister
	CodeInterpreterListerExpansion
}

// codeInterpreterLister implements the CodeInterpreterLister interface.
type codeInterpreterLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.CodeInterpreter]
}

// NewCodeInterpreterLister returns a new CodeInterpreterLister.
func NewCodeInterpreterLister(indexer cache.Indexer) CodeInterpreterLister {
	return &codeInterpreterLister{listers.New[*runtimev1alpha1.CodeInterpreter](indexer, runtimev1alpha1.Resource("codeinterpreter"))}
}

// CodeInterpreters returns an object that can list and get CodeInterpreters.
func (s *codeInterpreterLister) CodeInterpreters(namespace string) CodeInterpreterNamespaceLister {
	return codeInterpreterNamespaceLister{listers.NewNamespaced[*runtimev1alpha1.CodeInterpreter](s.ResourceIndexer, namespace)}
}

// CodeInterpreterNamespaceLister helps list and get CodeInterpreters.
// All objects returned here must be treated as read-only.
type CodeInterpreterNamespaceLister interface {
	// List lists all CodeInterpreters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.CodeInterpreter, err error)
	// Get retrieves the CodeInterpreter from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.CodeInterpreter, error)
	CodeInterpreterNamespaceListerExpansion
}

// codeInterpreterNamespaceLister implements the CodeInterpreterNamespaceLister
// interface.
type codeInterpreterNamespaceLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.CodeInterpreter]
}
