/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MultiAgentRuntimeLister helps list MultiAgentRuntimes.
// All objects returned here must be treated as read-only.
type MultiAgentRuntimeLister interface {
	// List lists all MultiAgentRuntimes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.MultiAgentRuntime, err error)
	// MultiAgentRuntimes returns an object that can list and get MultiAgentRuntimes.
	MultiAgentRuntimes(namespace string) MultiAgentRuntimeNamespaceLister
	MultiAgentRuntimeListerExpansion
}

// multiAgentRuntimeLister implements the MultiAgentRuntimeLister interface.
type multiAgentRuntimeLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.MultiAgentRuntime]
}

// NewMultiAgentRuntimeLister returns a new MultiAgentRuntimeLister.
func NewMultiAgentRuntimeLister(indexer cache.Indexer) MultiAgentRuntimeLister {
	return &multiAgentRuntimeLister{listers.New[*runtimev1alpha1.MultiAgentRuntime](indexer, runtimev1alpha1.Resource("multiagentruntime").GroupResource())}
}

// MultiAgentRuntimes returns an object that can list and get MultiAgentRuntimes.
func (s *multiAgentRuntimeLister) MultiAgentRuntimes(namespace string) MultiAgentRuntimeNamespaceLister {
	return multiAgentRuntimeNamespaceLister{listers.NewNamespaced[*runtimev1alpha1.MultiAgentRuntime](s.ResourceIndexer, namespace)}
}

// MultiAgentRuntimeNamespaceLister helps list and get MultiAgentRuntimes.
// All objects returned here must be treated as read-only.
type MultiAgentRuntimeNamespaceLister interface {
	// List lists all MultiAgentRuntimes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.MultiAgentRuntime, err error)
	// Get retrieves the MultiAgentRuntime from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.MultiAgentRuntime, error)
	MultiAgentRuntimeNamespaceListerExpansion
}

// multiAgentRuntimeNamespaceLister implements the MultiAgentRuntimeNamespaceLister
// interface.
type multiAgentRuntimeNamespaceLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.MultiAgentRuntime]
}
