/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SandboxSnapshotTaskLister helps list SandboxSnapshotTasks.
// All objects returned here must be treated as read-only.
type SandboxSnapshotTaskLister interface {
	// List lists all SandboxSnapshotTasks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.SandboxSnapshotTask, err error)
	// SandboxSnapshotTasks returns an object that can list and get SandboxSnapshotTasks.
	SandboxSnapshotTasks(namespace string) SandboxSnapshotTaskNamespaceLister
	SandboxSnapshotTaskListerExpansion
}

// sandboxSnapshotTaskLister implements the SandboxSnapshotTaskLister interface.
type sandboxSnapshotTaskLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.SandboxSnapshotTask]
}

// NewSandboxSnapshotTaskLister returns a new SandboxSnapshotTaskLister.
func NewSandboxSnapshotTaskLister(indexer cache.Indexer) SandboxSnapshotTaskLister {
	return &sandboxSnapshotTaskLister{listers.New[*runtimev1alpha1.SandboxSnapshotTask](indexer, runtimev1alpha1.Resource("sandboxsnapshottask").GroupResource())}
}

// SandboxSnapshotTasks returns an object that can list and get SandboxSnapshotTasks.
func (s *sandboxSnapshotTaskLister) SandboxSnapshotTasks(namespace string) SandboxSnapshotTaskNamespaceLister {
	return sandboxSnapshotTaskNamespaceLister{listers.NewNamespaced[*runtimev1alpha1.SandboxSnapshotTask](s.ResourceIndexer, namespace)}
}

// SandboxSnapshotTaskNamespaceLister helps list and get SandboxSnapshotTasks.
// All objects returned here must be treated as read-only.
type SandboxSnapshotTaskNamespaceLister interface {
	// List lists all SandboxSnapshotTasks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.SandboxSnapshotTask, err error)
	// Get retrieves the SandboxSnapshotTask from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.SandboxSnapshotTask, error)
	SandboxSnapshotTaskNamespaceListerExpansion
}

// sandboxSnapshotTaskNamespaceLister implements the SandboxSnapshotTaskNamespaceLister
// interface.
type sandboxSnapshotTaskNamespaceLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.SandboxSnapshotTask]
}
