/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SandboxSnapshotLister helps list SandboxSnapshots.
// All objects returned here must be treated as read-only.
type SandboxSnapshotLister interface {
	// List lists all SandboxSnapshots in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.SandboxSnapshot, err error)
	// SandboxSnapshots returns an object that can list and get SandboxSnapshots.
	SandboxSnapshots(namespace string) SandboxSnapshotNamespaceLister
	SandboxSnapshotListerExpansion
}

// sandboxSnapshotLister implements the SandboxSnapshotLister interface.
type sandboxSnapshotLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.SandboxSnapshot]
}

// NewSandboxSnapshotLister returns a new SandboxSnapshotLister.
func NewSandboxSnapshotLister(indexer cache.Indexer) SandboxSnapshotLister {
	return &sandboxSnapshotLister{listers.New[*runtimev1alpha1.SandboxSnapshot](indexer, runtimev1alpha1.Resource("sandboxsnapshot").GroupResource())}
}

// SandboxSnapshots returns an object that can list and get SandboxSnapshots.
func (s *sandboxSnapshotLister) SandboxSnapshots(namespace string) SandboxSnapshotNamespaceLister {
	return sandboxSnapshotNamespaceLister{listers.NewNamespaced[*runtimev1alpha1.SandboxSnapshot](s.ResourceIndexer, namespace)}
}

// SandboxSnapshotNamespaceLister helps list and get SandboxSnapshots.
// All objects returned here must be treated as read-only.
type SandboxSnapshotNamespaceLister interface {
	// List lists all SandboxSnapshots in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.SandboxSnapshot, err error)
	// Get retrieves the SandboxSnapshot from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.SandboxSnapshot, error)
	SandboxSnapshotNamespaceListerExpansion
}

// sandboxSnapshotNamespaceLister implements the SandboxSnapshotNamespaceLister
// interface.
type sandboxSnapshotNamespaceLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.SandboxSnapshot]
}
