/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SnapshotClassLister helps list SnapshotClasses.
// All objects returned here must be treated as read-only.
type SnapshotClassLister interface {
	// List lists all SnapshotClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.SnapshotClass, err error)
	// Get retrieves the SnapshotClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.SnapshotClass, error)
	SnapshotClassListerExpansion
}

// snapshotClassLister implements the SnapshotClassLister interface.
type snapshotClassLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.SnapshotClass]
}

// NewSnapshotClassLister returns a new SnapshotClassLister.
func NewSnapshotClassLister(indexer cache.Indexer) SnapshotClassLister {
	return &snapshotClassLister{listers.New[*runtimev1alpha1.SnapshotClass](indexer, runtimev1alpha1.Resource("snapshotclass").GroupResource())}
}
