{{- if and (not .Values.redis.secretName) .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-redis" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: agentcube
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.redis.secretKey | default "password" }}: {{ .Values.redis.password | quote }}
{{- end }}
