apiVersion: runtime.agentcube.volcano.sh/v1alpha1
kind: CodeInterpreter
metadata:
  name: my-interpreter
  namespace: default
spec:
  ports:
    - pathPrefix: "/"
      port: 8080
      protocol: "HTTP"
  template:
    image: ghcr.io/volcano-sh/picod:latest
    imagePullPolicy: IfNotPresent
    args:
      # The workspace directory will be created automatically by picod at startup
      - --workspace=/workspace
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  sessionTimeout: "15m"
  maxSessionDuration: "8h"
  warmPoolSize: 2