/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	versioned "github.com/volcano-sh/agentcube/client-go/clientset/versioned"
	internalinterfaces "github.com/volcano-sh/agentcube/client-go/informers/externalversions/internalinterfaces"
	runtimev1alpha1 "github.com/volcano-sh/agentcube/client-go/listers/runtime/v1alpha1"
	apisruntimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentRuntimeInformer provides access to a shared informer and lister for
// AgentRuntimes.
type AgentRuntimeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() runtimev1alpha1.AgentRuntimeLister
}

type agentRuntimeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentRuntimeInformer constructs a new informer for AgentRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAgentRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAgentRuntimeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAgentRuntimeInformer constructs a new informer for AgentRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAgentRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().AgentRuntimes(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().AgentRuntimes(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().AgentRuntimes(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().AgentRuntimes(namespace).Watch(ctx, options)
			},
		},
		&apisruntimev1alpha1.AgentRuntime{},
		resyncPeriod,
		indexers,
	)
}

func (f *agentRuntimeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAgentRuntimeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *agentRuntimeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisruntimev1alpha1.AgentRuntime{}, f.defaultInformer)
}

func (f *agentRuntimeInformer) Lister() runtimev1alpha1.AgentRuntimeLister {
	return runtimev1alpha1.NewAgentRuntimeLister(f.Informer().GetIndexer())
}
