{{- if .Values.spire.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: spiffe-helper
data:
  spiffe-helper.conf: |
    agent_address = "/run/spire/sockets/agent.sock"
    cmd = ""
    cmd_args = ""
    cert_dir = "{{ .Values.spire.spiffeHelper.certDir }}"
    renew_signal = "SIGHUP"
    svid_file_name = "{{ .Values.spire.spiffeHelper.certFileName }}"
    svid_key_file_name = "{{ .Values.spire.spiffeHelper.keyFileName }}"
    svid_bundle_file_name = "{{ .Values.spire.spiffeHelper.bundleFileName }}"
    # Allow non-root app containers (via fsGroup) to read the private key
    key_file_mode = "0640"
{{- end }}
