apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: codeinterpreters.runtime.agentcube.io
  labels:
    app: agentcube
spec:
  group: runtime.agentcube.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              ports:
                type: array
                items:
                  type: object
                  properties:
                    pathPrefix:
                      type: string
                    name:
                      type: string
                    port:
                      type: integer
                      format: int32
                    protocol:
                      type: string
                      enum:
                      - HTTP
                      - HTTPS
                      default: HTTP
                  required:
                  - port
                  - protocol
              template:
                type: object
                required:
                - image
                properties:
                  labels:
                    type: object
                    additionalProperties:
                      type: string
                  annotations:
                    type: object
                    additionalProperties:
                      type: string
                  runtimeClassName:
                    type: string
                  image:
                    type: string
                  environment:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                        valueFrom:
                          type: object
                      required:
                      - name
                  command:
                    type: array
                    items:
                      type: string
                  args:
                    type: array
                    items:
                      type: string
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        additionalProperties:
                          type: string
                      requests:
                        type: object
                        additionalProperties:
                          type: string
              sessionTimeout:
                type: string
                default: "15m"
              maxSessionDuration:
                type: string
                default: "8h"
              languages:
                type: array
                items:
                  type: string
              warmPoolSize:
                type: integer
                format: int32
            required:
            - template
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    observedGeneration:
                      type: integer
                      format: int64
              ready:
                type: boolean
              activeSessions:
                type: integer
                format: int32
              warmPoolReady:
                type: integer
                format: int32
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: codeinterpreters
    singular: codeinterpreter
    kind: CodeInterpreter
    shortNames:
    - ci

