name: Python SDK Tests

on:
  push:
    # Exclude branches created by Dependabot to avoid triggering current workflow
    # for PRs initiated by Dependabot.
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: read

jobs:
  python-sdk-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk-python

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            sdk:
              - 'sdk-python/**'

      - name: Setup Python
        if: steps.changes.outputs.sdk == 'true'
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        if: steps.changes.outputs.sdk == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run unit tests
        if: steps.changes.outputs.sdk == 'true'
        run: |
          python -m pytest tests/ -v
