name: Test Coverage

on:
  push:
    # Exclude branches created by Dependabot to avoid triggering current workflow
    # for PRs initiated by Dependabot.
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  merge_group: # enable merge queue
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read
  pull-requests: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        with:
          filters: |
            coverage:
              - '**'
              - '!**/*.md'
              - '!**/*.svg'
              - '!**/*.png'

      - name: Free Disk Space
        if: steps.changes.outputs.coverage == 'true'
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Setup Go
        if: steps.changes.outputs.coverage == 'true'
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod

      - name: Run tests with coverage
        if: steps.changes.outputs.coverage == 'true'
        run: |
          go test -race -v -coverprofile=coverage.out -coverpkg=./pkg/... ./pkg/...

      - name: Display coverage summary
        if: steps.changes.outputs.coverage == 'true'
        run: |
          echo "## Go Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          go tool cover -func=coverage.out >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Coverage Summary" >> $GITHUB_STEP_SUMMARY
          go tool cover -func=coverage.out | tail -1 >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage reports to Codecov
        if: steps.changes.outputs.coverage == 'true'
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          # Even though token upload token is not required for public repos,
          # but adding a token might increase successful uploads as per:
          # https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: unittests
          fail_ci_if_error: false
          verbose: true

      - name: Upload coverage artifact
        if: steps.changes.outputs.coverage == 'true'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: go-coverage
          path: coverage.out
